const words = [
    {en:"Apple", az:"Alma"},
    {en:"Book", az:"Kitab"},
    {en:"Car", az:"Maşın"},
    {en:"Dog", az:"İt"},
    {en:"Cat", az:"Pişik"},
    {en:"House", az:"Ev"},
    {en:"Water", az:"Su"},
    {en:"Sun", az:"Günəş"},
    {en:"Moon", az:"Ay"},
    {en:"School", az:"Məktəb"},
    {en:"Chair", az:"Stul"},
    {en:"Table", az:"Masa"},
    {en:"Pen", az:"Qələm"},
    {en:"Pencil", az:"Rəngli qələm"},
    {en:"Notebook", az:"Dəftər"},
    {en:"Bag", az:"Çanta"},
    {en:"Window", az:"Pəncərə"},
    {en:"Door", az:"Qapı"},
    {en:"Street", az:"Küçə"},
    {en:"Carpet", az:"Xalça"},
    {en:"Tree", az:"Ağac"},
    {en:"Flower", az:"Gül"},
    {en:"Bird", az:"Quş"},
    {en:"Fish", az:"Balıq"},
    {en:"Chair", az:"Stul"},
    {en:"Bread", az:"Çörək"},
    {en:"Milk", az:"Süd"},
    {en:"Coffee", az:"Qəhvə"},
    {en:"Tea", az:"Çay"},
    {en:"Sugar", az:"Şəkər"},
    {en:"Salt", az:"Duz"},
    {en:"Butter", az:"Kərə yağı"},
    {en:"Egg", az:"Yumurta"},
    {en:"Meat", az:"Ət"},
    {en:"Chicken", az:"Toyuq"},
    {en:"Fish", az:"Balıq"},
    {en:"Fruit", az:"Meyvə"},
    {en:"Vegetable", az:"Tərəvəz"},
    {en:"Apple", az:"Alma"},
    {en:"Banana", az:"Banan"},
    {en:"Orange", az:"Portağal"},
    {en:"Grape", az:"Üzüm"},
    {en:"Strawberry", az:"Çiyələk"},
    {en:"Carrot", az:"Kök"},
    {en:"Tomato", az:"Pomidor"},
    {en:"Potato", az:"Kartof"},
    {en:"Onion", az:"Soğan"},
    {en:"Garlic", az:"Sarımsaq"},
    {en:"Rice", az:"Düyü"},
    {en:"Soup", az:"Şorba"},
    {en:"Cheese", az:"Pendirlər"},
    {en:"Chair", az:"Stul"},
    {en:"Bed", az:"Çarpayı"},
    {en:"Sofa", az:"Divan"},
    {en:"TV", az:"Televizor"},
    {en:"Computer", az:"Kompyuter"},
    {en:"Phone", az:"Telefon"},
    {en:"Clock", az:"Saat"},
    {en:"Bag", az:"Çanta"},
    {en:"Shoes", az:"Ayaqqabı"},
    {en:"Shirt", az:"Köynək"},
    {en:"Pants", az:"Şalvar"},
    {en:"Hat", az:"Papaq"},
    {en:"Glasses", az:"Eynək"},
    {en:"Sun", az:"Günəş"},
    {en:"Moon", az:"Ay"},
    {en:"Star", az:"Ulduz"},
    {en:"Sky", az:"Səma"},
    {en:"Cloud", az:"Bulud"},
    {en:"Rain", az:"Yağış"},
    {en:"Snow", az:"Qar"},
    {en:"Wind", az:"Külək"},
    {en:"Fire", az:"Od"},
    {en:"Water", az:"Su"},
    {en:"Earth", az:"Torpaq"},
    {en:"Air", az:"Hava"},
    {en:"Mountain", az:"Dağ"},
    {en:"River", az:"Çay"},
    {en:"Sea", az:"Dəniz"},
    {en:"Ocean", az:"Okean"},
    {en:"Forest", az:"Meşə"},
    {en:"Desert", az:"Səhra"},
    {en:"Island", az:"Ada"},
    {en:"City", az:"Şəhər"},
    {en:"Village", az:"Kənd"},
    {en:"Road", az:"Yol"},
    {en:"Bridge", az:"Körpü"},
    {en:"Car", az:"Maşın"},
    {en:"Bus", az:"Avtobus"},
    {en:"Train", az:"Qatar"},
    {en:"Plane", az:"Təyyarə"},
    {en:"Bicycle", az:"Velosiped"},
    {en:"Motorcycle", az:"Motosikl"},
    {en:"Taxi", az:"Taksi"},
    {en:"Doctor", az:"Həkim"},
    {en:"Nurse", az:"Tibb bacısı"},
    {en:"Teacher", az:"Müəllim"},
    {en:"Student", az:"Tələbə"},
    {en:"Police", az:"Polis"},
    {en:"Firefighter", az:"Yanğınsöndürən"},
    {en:"Driver", az:"Sürücü"},
    {en:"Engineer", az:"Mühəndis"},
    {en:"Artist", az:"Rəssam"},
    {en:"Musician", az:"Musiqiçi"},
    {en:"Actor", az:"Aktör"},
    {en:"Singer", az:"Müğənni"},
    {en:"Writer", az:"Yazıçı"},
    {en:"Painter", az:"Rəssam"},
    {en:"Cook", az:"Aşpaz"},
    {en:"Farmer", az:"Fərmer"},
    {en:"Worker", az:"İşçi"},
    {en:"Manager", az:"Menecer"},
    {en:"President", az:"Prezident"},
    {en:"King", az:"Kral"},
    {en:"Queen", az:"Kraliça"}
];
let current=0, showEn=true;

function flipCard(){
    const card=document.getElementById("cardText");
    card.innerText = showEn ? words[current].az : words[current].en;
    showEn=!showEn;
}

function nextCard(){
    current=(current+1)%words.length;
    document.getElementById("cardText").innerText=words[current].en;
    showEn=true;
}